# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packet.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='packet.proto',
  package='txrudp',
  serialized_pb='\n\x0cpacket.proto\x12\x06txrudp\"\xbd\x01\n\x06Packet\x12\x0b\n\x03syn\x18\x01 \x01(\x08\x12\x0b\n\x03\x66in\x18\x02 \x01(\x08\x12\x17\n\x0fsequence_number\x18\x03 \x01(\x04\x12\x16\n\x0emore_fragments\x18\x04 \x01(\x04\x12\x0b\n\x03\x61\x63k\x18\x05 \x01(\x04\x12\x0f\n\x07payload\x18\x06 \x01(\x0c\x12\x0f\n\x07\x64\x65st_ip\x18\x07 \x02(\t\x12\x11\n\tdest_port\x18\x08 \x02(\r\x12\x11\n\tsource_ip\x18\t \x02(\t\x12\x13\n\x0bsource_port\x18\n \x02(\rB\x02H\x03')




_PACKET = _descriptor.Descriptor(
  name='Packet',
  full_name='txrudp.Packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='syn', full_name='txrudp.Packet.syn', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fin', full_name='txrudp.Packet.fin', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sequence_number', full_name='txrudp.Packet.sequence_number', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='more_fragments', full_name='txrudp.Packet.more_fragments', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ack', full_name='txrudp.Packet.ack', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='txrudp.Packet.payload', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dest_ip', full_name='txrudp.Packet.dest_ip', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dest_port', full_name='txrudp.Packet.dest_port', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source_ip', full_name='txrudp.Packet.source_ip', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source_port', full_name='txrudp.Packet.source_port', index=9,
      number=10, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=214,
)

DESCRIPTOR.message_types_by_name['Packet'] = _PACKET

class Packet(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PACKET

  # @@protoc_insertion_point(class_scope:txrudp.Packet)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003')
# @@protoc_insertion_point(module_scope)
